name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: easy-edge-linux-x64
            executable_path: dist/easy-edge
          - os: macos-latest
            artifact_name: easy-edge-macos-x64
            executable_path: dist/easy-edge
          - os: windows-latest
            artifact_name: easy-edge-windows-x64.exe
            executable_path: dist/easy-edge.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        python build.py

    - name: Create checksum
      run: |
        cd dist
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          certutil -hashfile easy-edge.exe SHA256 > easy-edge.exe.sha256
        else
          sha256sum easy-edge > easy-edge.sha256
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          ${{ matrix.executable_path }}
          dist/*.sha256

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          easy-edge-linux-x64/easy-edge
          easy-edge-linux-x64/*.sha256
          easy-edge-macos-x64/easy-edge
          easy-edge-macos-x64/*.sha256
          easy-edge-windows-x64.exe/easy-edge.exe
          easy-edge-windows-x64.exe/*.sha256
        generate_release_notes: true
        draft: false
        prerelease: false 